[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "astro"
  targetPort = 4321